import '../styles/globals.css';
import type { AppProps } from 'next/app';
import { ThemeProvider } from 'styled-components';
import Head from 'next/head';
import Navigation from '../components/navigation';
import Page from '../containers/page';
import { observer } from 'mobx-react';
import store from '../store';

const MyApp = observer(({ Component, pageProps }: AppProps) => {
  return (
    <ThemeProvider theme={store.theme}>
      <Page>
        <Navigation />
        <Head>
          <title>Demo Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </Page>
    </ThemeProvider>
  );
});

export default MyApp;
