import '../styles/globals.css';
import type { AppProps } from 'next/app';
import { ThemeProvider } from 'styled-components';
import Head from 'next/head';
import Navigation from '../components/navigation';
import Page from '../containers/page';
import theme from '../styles/theme';
import { useState } from 'react';

function MyApp({ Component, pageProps }: AppProps) {
  const [currentTheme, setCurrentTheme] = useState(theme);
  const toggleTheme = () => {
    if (currentTheme.current.name === 'light') {
      setCurrentTheme({ ...theme, current: theme.dark });
    } else {
      setCurrentTheme({ ...theme, current: theme.light });
    }
  };
  return (
    <ThemeProvider theme={currentTheme}>
      <Page>
        <Navigation
          toggleTheme={toggleTheme}
        />
        <Head>
          <title>Demo Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </Page>
    </ThemeProvider>
  );
}

export default MyApp;
