import { observer } from "mobx-react";
import '../styles/globals.css';
import type { AppProps } from 'next/app';
import { ThemeProvider } from 'styled-components';
import Head from 'next/head';
import Navigation from '../components/navigation';
import Page from '../containers/page';
import theme from '../styles/theme';
import { useState } from 'react';
import { NextDemoAppStore } from '../stores';

const store = new NextDemoAppStore;

function MyApp({ Component, pageProps }: AppProps) {
  const [currentTheme, setCurrentTheme] = useState(theme);
  const toggleTheme = () => {
    store.themeStore.toggleTheme();
  };
  return (
    <ThemeProvider theme={store.themeStore.theme}>
      <Page>
        <Navigation
          toggleTheme={toggleTheme}
        />
        <Head>
          <title>Demo Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </Page>
    </ThemeProvider>
  );
}

export default observer(MyApp);
