import type { NextPage } from 'next';
import { ThemeProvider } from 'react-bootstrap';
import Head from 'next/head';
import Navigation from '../components/navigation';
import Page from '../containers/page';
import theme from '../styles/theme';
import styles from '../styles/Home.module.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import { StyledPage } from '../containers/page/page';

const Home: NextPage = () => {
  return (
    <ThemeProvider theme={theme}>
      <StyledPage>
        <div className={styles.container}>
          <Navigation />
          <Head>
            <title>Demo Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </div>
      </StyledPage>
    </ThemeProvider>

  );
};

export default Home;
