import type { NextPage } from 'next';
import { ThemeProvider } from 'styled-components';
import Head from 'next/head';
import Navigation from '../components/navigation';
import Page from '../containers/page';
import theme from '../styles/theme';

const Home: NextPage = () => {
  return (
    <ThemeProvider theme={theme}>
      <Page>
        <Navigation />
        <Head>
          <title>Demo Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </Page>
    </ThemeProvider>
  );
};

export default Home;
